config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  concern :tagging do
    collection do
      get :tagging
      post :update_tags
    end
  end

  root to: 'books#index'
  resources :books do
    concerns :tagging
  end
  resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  include Taggable
  include Uuid
  include BookFilters

  validates :title, presence: true
  validates :uuid, presence: true, on: :save

  def to_s
    title
  end
end

app/models/concerns/book_filters.rb
# frozen_string_literal: true

module BookFilters
  extend ActiveSupport::Concern
  included do
    scope :title_cont, ->(title) { where("title LIKE '%#{title}%'") }
    scope :tags_name_in, ->(names) { distinct.joins(:tags).where({ tags: { name: names } }) }
    scope :price_lteq, ->(min) { where('price <= ?', min) }
    scope :price_gteq, ->(max) { where('price >= ?', max) }

    class << self
      def build_filters(params)
        return self unless params

        klass = self
        klass = klass.title_cont(params[:title_cont]) if  params[:title_cont].present?
        klass = klass.tags_name_in(params[:tags_name_in]) if params[:tags_name_in].present?
        klass = klass.price_gteq(params[:price_gteq]) if  params[:price_gteq].present?
        klass = klass.price_lteq(params[:price_lteq]) if  params[:price_lteq].present?
        klass
      end
    end
  end
end

app/models/concerns/taggable.rb
# frozen_string_literal: true

module Taggable
  extend ActiveSupport::Concern
  included do
    has_many :taggings, as: :taggable
    has_many :tags, through: :taggings, counter_cache: true

    accepts_nested_attributes_for :taggings
    accepts_nested_attributes_for :tags

    def tag_names
      tags.pluck(:name)
    end
  end
end

app/models/concerns/uuid.rb
# frozen_string_literal: true

module Uuid
  extend ActiveSupport::Concern
  included do
    before_create :set_uuid

    def set_uuid
      self.uuid = SecureRandom.uuid
    end
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggables, class_name: 'Tagging', foreign_key: :taggable_id
  has_many :books, through: :taggables, source: :taggable, source_type: 'Book'

  def to_s
    name
  end

  class << self
    def names
      pluck(:name)
    end
  end
end

app/models/tagging.rb
# frozen_string_literal: true

class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :taggable, polymorphic: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  include TaggableActions
  before_action :set_book, only: %i[show edit update destroy]

  def index
    params[:tags_name_in] = params[:tags_name_in].split(',') if params[:tags_name_in]
    @books = Book.build_filters(params).all
  end

  def show; end

  def new
    @book = Book.new
  end

  def edit; end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :price)
  end
end

app/controllers/concerns/taggable_actions.rb
# frozen_string_literal: true

module TaggableActions
  extend ActiveSupport::Concern

  included do
    before_action :set_resources, only: %i[tagging update_tags]

    def tagging; end

    def update_tags
      @tags = params[:tag_list]&.split(',')
      @books_ids = params[:taggables]
      create_new_tags
      set_book_tags
      render :tagging
    end

    def set_resources
      @tags = Tag.all
      @objects = model_class.all
    end

    private

    def create_new_tags
      (@tags - Tag.names).each do |tag|
        Tag.create!(name: tag)
      end
    end

    def set_book_tags
      @tags.each do |tag|
        @tag = Tag.find_by_name(tag)
        @books_ids.each do |book_id|
          book = Book.find_by_id(book_id)
          next if book && book.taggings.where(tag_id: @tag.id).exists?

          book.taggings.create!(tag_id: @tag.id)
        end
      end
    end

    def model_class
      controller_name.classify.constantize
    end
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]

  def index
    @tags = Tag.all
  end

  def show; end

  def new
    @tag = Tag.new
  end

  def edit; end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/helpers/tagging_helper.rb
# frozen_string_literal: true

module TaggingHelper
end

app/helpers/taggings_helper.rb
# frozen_string_literal: true

module TaggingsHelper
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/books/_form.html.haml
= form_with(model: book, local: true) do |form|
  - if book.errors.any?
    #error_explanation
      %h2
        = pluralize(book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - book.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :description
    = form.text_area :description
  .field
    = form.label :price
    = form.number_field :price
  .actions
    = form.submit

app/views/books/edit.html.haml
%h1 Editing Book
= render 'form', book: @book
= link_to 'Show', @book
|
= link_to 'Back', books_path

app/views/books/index.html.haml
%p#notice= notice
.row
  .col-6
    %h1 Books
  .col-6.justify-content-end.text-right
    = link_to 'New Book', new_book_path, class: 'btn btn-info m-4'
    = link_to 'Mange Taggings', tagging_books_path, class: 'btn btn-info m-4', 'data-turbolinks': "false"
= form_with url: books_path, method: :get,local: true do |f|
  .row
    .col-md-2
      .form-group
        = f.label :title_cont
        = f.search_field :title_cont, value: params[:title_cont], class: 'form-control'
    .col-md-4
      .row
        .col-md-6
          .form-group
            = f.label :price_greater_than
            = f.number_field :price_gteq, value: params[:price_gteq],  class: 'form-control'
        .col-md-6
          .form-group
            = f.label :price_less_than
            = f.number_field :price_lteq, value: params[:price_lteq], class: 'form-control'
    .col-md-4
      .form-group
        = f.label :Tags
        = f.text_field :tags_name_in, value: params.dig(:tags_name_in)&.join(','), class: 'form-control','data-role': 'tagsinput'
    .col-md-2
      .form-group.mt-4
        = f.submit :search, class: 'btn btn-primary form-control'
%table.table
  %thead
    %tr
      %th Title
      %th Description
      %th Uuid
      %th Price
      %th Tags
      %th{:colspan => "3"} Actions
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.description
        %td= book.uuid
        %td
          - if book.price > 0
            .badge.badge-info.p-2
              $ #{book.price}
          - else
            .badge.badge-success.p-2 Free
        %td= book.tags.pluck(:name).join(',')
        %td= link_to 'Show', book
        %td= link_to 'Edit', edit_book_path(book)
        %td= link_to 'Destroy', book, method: :delete, data: {confirm: 'Are you sure?'}
%br/

app/views/books/new.html.haml
%h1 New Book
= render 'form', book: @book
= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice
%p
  %strong Uuid:
  = @book.uuid
%p
  %strong Title:
  = @book.title
%p
  %strong Description:
  = @book.description
%p
  %strong Price:
  = @book.price
= link_to 'Edit', edit_book_path(@book)
|
= link_to 'Back', books_path

app/views/books/tagging.html.haml
- content_for(:body_attributes) do
  data-turbolinks="false"
.row.m-4
  .col-6
    %h1 Tags
  .col-6.justify-content-end.text-right
    = link_to 'Back To Books', books_path, class: 'btn btn-info m-4', 'data-turbolinks': "false"
.row.m-4
  .col-12
    = form_with(url: update_tags_books_path, method: :post, local: true) do |form|
      = form.label :tag_list
      = form.text_field :tag_list,value: Tag.names.join(','),'data-role': 'tagsinput'
      %hr/
      = form.label :books_to_assign_label
      %table.table.table-bordered.table-sm
        - @objects.each do |object|
          %tr
            %td
              = label_tag :taggables, object
            %td= object.description
            %td= check_box_tag 'taggables[]', object.id, false
      = form.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BookApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/tags/_form.html.haml
= form_with(model: tag, local: true) do |form|
  - if tag.errors.any?
    #error_explanation
      %h2
        = pluralize(tag.errors.count, "error")
        prohibited this tag from being saved:
      %ul
        - tag.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :description
    = form.text_field :description
  .actions
    = form.submit

app/views/tags/edit.html.haml
%h1 Editing Tag
= render 'form', tag: @tag
= link_to 'Show', @tag
|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
%p#notice= notice
%h1 Tags
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @tags.each do |tag|
      %tr
        %td= tag.name
        %td= tag.description
        %td= link_to 'Show', tag
        %td= link_to 'Edit', edit_tag_path(tag)
        %td= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Tag', new_tag_path

app/views/tags/new.html.haml
%h1 New Tag
= render 'form', tag: @tag
= link_to 'Back', tags_path

app/views/tags/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @tag.name
%p
  %strong Description:
  = @tag.description
= link_to 'Edit', edit_tag_path(@tag)
|
= link_to 'Back', tags_path